### ISSUE TITLE
s2i : add extra steps to get s2i image builder labels 

### ISSUE THREAD

**Issue by vdemeester** [openshift/pipelines-catalog#3]
Related to https://github.com/openshift/source-to-image/issues/973, `s2i build --as-dockerfile` doesn't read those labels, and thus some s2i can later failed if the runtime script are not at the default places.

As a temporary workaround, we should add a `skopeo` inspect step that gets those labels, so that we can specify the correct flags to `s2i build --as-dockerfile` :angel: 

cc @piyush-garg @siamaksade

**Comment by siamaksade** [comment]
It might be more relevant for the [generic s2i task in tektoncd/catalog](https://github.com/tektoncd/catalog/tree/master/s2i)? 

Given that in runtime-specific tasks we know which builder image is building used and can pass the correct params to `s2i build`.

**Comment by vdemeester** [comment]
ohh good point, we definitely need that on the upstream catalog too, let me create an issue there too
