### ISSUE TITLE
Use rhel builder images instead of centos

### ISSUE THREAD

**Issue by siamaksade** [openshift/pipelines-catalog#4]

**Comment by lance** [comment]
Do you mean RHOAR RHEL builder images? Or RHOAR CentOS? Both are available, but the RHEL images require a subscription. CentOS are community. 

* RHEL: https://access.redhat.com/containers/?tab=overview#/registry.access.redhat.com/rhoar-nodejs/nodejs-10
* Community: https://hub.docker.com/r/nodeshift/centos7-s2i-nodejs

/cc @lholmquist @ladicek

**Comment by Ladicek** [comment]
I don't have a say in this, but I really think RHOAR Node.js should be used (be it RHEL or CentOS).

**Comment by siamaksade** [comment]
@Ladicek @lance as I understand, quite soon there will be a one set of images supported (no SCL vs RHOAR). If that's the case, the task should use those images whichever that they become

**Comment by Ladicek** [comment]
That would be great :-)

**Comment by lance** [comment]
Agree - it will be great when we get to this point. :) 

We've been saying "soon" for a long time, but I expect we should have this smoothed out in a few weeks.

**Comment by piyush-garg** [comment]
resolved using #10
