### ISSUE TITLE
s2i Task description should not claim to clone git

### ISSUE THREAD

**Issue by tux-o-matic** [openshift/pipelines-catalog#70]
The s2i *Tasks* have in their description:
[...] task `clones a Git repository` and builds and pushes a container image using S2I [...]

Which is a misleading claim since those s2i *Tasks* rely on a `git-clone` *Task* to run before in a pipeline and output source to a shared workspace.

**Comment by nikhil-thomas** [comment]
/remove-lifecycle rotten
issue still exists
/assign @nikhil-thomas
